game:
  initialization_mode: "single_alive_cell" # Options: ["single_alive_cell", "single_dead_cell", "random"]
  boundary_mode: "periodic" # Options: ["zero", "periodic", "reflective"]
  rule_set: 89 # Ranges 0-255.
  fps: 60

window:
  caption: "Elementary Cellular Automaton"
  background_color: [245, 245, 240] # RGB-values.
  margin_size: 200 # Units: pixels.

grid:
  dim: 101 # Number of cells in width as well as height direction. Must be an odd number.
  color_map:
    0: [35, 35, 35] # `0` represent dead cells.
    1: [190, 55, 55] # `1` represent alive cells.
  show_gridlines: False # Optionally enable gridlines.
  grid_line_color: [150, 150, 150]
  grid_line_width: 2 # Units: pixels.